p8105\_hw1\_raj2152
================
Rachelle Juan
9/26/2021

## Problem 1

First, create a data frame and show resulting output table.

``` r
set.seed(1)

df = tibble(
  rand_sample = rnorm(10),
  logical_vec = rand_sample > 0,
  char_vec = c("This","is","homework","1","for","Data","Science","with","Jeff","Goldsmith"),
  factor_vec = factor(c("male","female","other","other","female","other","female","male","male","female"))
)

df
```

    ## # A tibble: 10 × 4
    ##    rand_sample logical_vec char_vec  factor_vec
    ##          <dbl> <lgl>       <chr>     <fct>     
    ##  1      -0.626 FALSE       This      male      
    ##  2       0.184 TRUE        is        female    
    ##  3      -0.836 FALSE       homework  other     
    ##  4       1.60  TRUE        1         other     
    ##  5       0.330 TRUE        for       female    
    ##  6      -0.820 FALSE       Data      other     
    ##  7       0.487 TRUE        Science   female    
    ##  8       0.738 TRUE        with      male      
    ##  9       0.576 TRUE        Jeff      male      
    ## 10      -0.305 FALSE       Goldsmith female

Try to take the mean of each variable in the data frame, after pulling
each one:

``` r
mean(pull(df,rand_sample))
```

    ## [1] 0.1322028

``` r
mean(pull(df,logical_vec))
```

    ## [1] 0.6

``` r
mean(pull(df,char_vec))
```

    ## Warning in mean.default(pull(df, char_vec)): argument is not numeric or logical:
    ## returning NA

    ## [1] NA

``` r
mean(pull(df,factor_vec))
```

    ## Warning in mean.default(pull(df, factor_vec)): argument is not numeric or
    ## logical: returning NA

    ## [1] NA

I could only get the mean for rand\_sample and the logical\_vec
variables. The character and factor variables returned ‘NA’ and gave a
warning that the argument is not numeric or logical.

Attempt to convert variable types to numeric.

``` r
as.numeric(pull(df,logical_vec))
as.numeric(pull(df,char_vec))
as.numeric(pull(df,factor_vec))
```

The logical variable converts to numeric boolean values (1 if True, 0 if
false). The character variable converted the values to ‘NA’ and gave the
warning that ‘NAs introduced by coercion’. The factor variable converted
each value level to a numeric value. This explains why we’re able to get
a mean for logical but not character and factor variables. However, now
that the factor variable has numeric values we are able to take the
mean.

## Problem 2

Load the penguins dataset.

``` r
data("penguins", package = "palmerpenguins")
```

The names of all the variables in the penguins dataset include:

``` r
names(penguins)
```

    ## [1] "species"           "island"            "bill_length_mm"   
    ## [4] "bill_depth_mm"     "flipper_length_mm" "body_mass_g"      
    ## [7] "sex"               "year"

We see that there are 8 variables in the dataset (hence, 8 columns) with
specific measurements for penguins – including, species, island, bill
and flipper measurements, and sex of each penguin. It seems that each
row is an observation of an individual penguin. We can also examine some
of the values of these variables:

``` r
head(penguins, 5)
```

    ## # A tibble: 5 × 8
    ##   species island bill_length_mm bill_depth_mm flipper_length_… body_mass_g sex  
    ##   <fct>   <fct>           <dbl>         <dbl>            <int>       <int> <fct>
    ## 1 Adelie  Torge…           39.1          18.7              181        3750 male 
    ## 2 Adelie  Torge…           39.5          17.4              186        3800 fema…
    ## 3 Adelie  Torge…           40.3          18                195        3250 fema…
    ## 4 Adelie  Torge…           NA            NA                 NA          NA <NA> 
    ## 5 Adelie  Torge…           36.7          19.3              193        3450 fema…
    ## # … with 1 more variable: year <int>

``` r
nrow(penguins)
```

    ## [1] 344

``` r
ncol(penguins)
```

    ## [1] 8

There are 344 rows and 8 columns in the penguin dataset, meaning there
are 8 variables of interest and 344 observations of penguins.

We can also find the mean flipper length, in millimeters:

``` r
mean(pull(penguins, flipper_length_mm), na.rm = TRUE)
```

    ## [1] 200.9152

The mean flipper length is around 201 mm.

### Scatterplot

Now, we’ll make a scatterplot of flipper length (y) by bill length (x).

``` r
ggplot(penguins, aes(x = bill_length_mm, y = flipper_length_mm, color = species)) + geom_point()
```

![](p8105_hw1_raj2152_files/figure-gfm/unnamed-chunk-10-1.png)<!-- -->

``` r
ggsave("scatterplot.pdf", height = 4, width = 6)
```
